#!/bin/bash
# Shared bash functions for the tool scripts

__DIRNAME="$(dirname "$(readlink -f "$0")")"

function _white() {
	echo -e "\033[37m$*\033[m"
}

function _bold() {
	echo -e "\033[1m$*\033[m"
}

function _yellow() {
	echo -e "\033[33m$*\033[m"
}

function _red() {
	echo -e "\033[31m$*\033[m"
}

function _blue() {
	echo -e "\033[34m$*\033[m"
}

function log() {
	echo "$(_blue ➤) $*"
}

function error() {
	echo "$(_red ●) $(_bold $*)" >&2
	exit 1
}

function updateVersionFiles() {
	# Only run once per batch run
	if [ "$_UPDATE_VERSION_FILES_DONE" = "1" ]; then
		return
	fi
	export _UPDATE_VERSION_FILES_DONE=1

	BUILDTIME=$(date +%s)
	getVersion

	(cat - >${__DIRNAME}/../version.go) <<EOF
package main

// ==========================================================================
// DO NOT CHANGE THIS FILE, THIS FILE IS AUTOGENERATED BY THE BUILD/DEV TOOLS
// ==========================================================================

// Version is the current version of the application
const Version = "$VERSION"
const HumanVersion = "$HUMAN_VERSION"
const BUILDTIME = $BUILDTIME
EOF
}

CURRENTOS=$(uname -s)

#if command -v curl >/dev/null 2>&1; then
#	DOWNLOAD=("curl" "-sL")
#elif command -v wget >/dev/null 2>&1; then
#	DOWNLOAD=("wget" "-qO-")
#else
#	echo "Neither wget nor curl found. Please install one of these." >&2
#	exit 1
#fi

#function download() {
#	# Only output to log if download fails
#	"${DOWNLOAD[@]}" "$1" >"$2" || false
#}

function getVersion() {
	# Only run once per batch run
	if [ "$_GET_VERSION_DONE" = "1" ]; then
		return
	fi
	export _GET_VERSION_DONE=1
	export VERSION_BUILD="$(git rev-list --count HEAD)"

	# Get current branch if not set
	: "${BRANCH:="$(git rev-parse --abbrev-ref HEAD)"}"
	export BRANCH

	if [[ "$(git describe --exact-match --tags 2>/dev/null)" = v* ]]; then
		export BRANCH="stable"
	fi

	# jq is used when available; fall back to sed so a plain clone builds without it.
	if command -v jq >/dev/null 2>&1; then
		CUR=$(jq -r .version "${__DIRNAME}/../version.json" 2>/dev/null)
	else
		CUR=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "${__DIRNAME}/../version.json")
	fi
	if [ -z "$CUR" ] || [ "$CUR" = "null" ]; then
		error "Failed to get version from version.json"
	fi
	VER="$(echo $CUR | cut -d- -f1)"
	VERSION_HASH="$(git rev-parse --short=8 HEAD)"
	export VERSION="${VER}+${VERSION_BUILD}-${BRANCH}-${VERSION_HASH}"

	if [ "$BRANCH" = "stable" ]; then
		export HUMAN_VERSION="${VER}"
	else
		export HUMAN_VERSION="${VER}+${VERSION_BUILD}-${BRANCH}-${VERSION_HASH}"
	fi
	export VERSION_MAJOR=$(echo $VER | cut -d. -f1)
	export VERSION_MINOR=$(echo $VER | cut -d. -f2)
	export VERSION_PATCH=$(echo $VER | cut -d. -f3)
}